### PR TITLE
Make default

### PR DESCRIPTION
**Pull request by dougmet**
Nigel told me about this code, it looks really nice. I thought I'd test it out but I had to make one or two small tweaks to get it to compile/run. I thought you might like them back here. The idea is that the code will run out-of-the-box after compiling (with a new Makefile) and running with the default datasets.

Feel free to ignore the PR.

* Changes to `Program.c` to use the csv files shipped with the code.
* New (basic) `Makefile` handles `randvec.c` and creates `spa.out`.
* Updated README with instructions.
* A new `.gitignore` to stop binaries ending up in the repo.

The output that I get with this is pasted below. Does it look OK for the demo data? I'm a bit concerned about the 32767 at the end.

```
1,36,3
2,30,3
3,6,1
4,5,1
5,24,1
6,52,1
7,14,3
8,27,1
9,21,1
10,4,1
11,37,1
12,47,2
13,22,1
14,57,1
15,51,2
16,2,3
17,34,1
18,15,2
19,44,2
20,1,32767
Final energy: -85.425537
```

### CODE REVIEW

**Comment by dougmet** [comment]
Just realised you probably don't want to change the code as it's a paper. So feel free to close this. I didn't change anything except for the input files and adding the Makefile.

**Comment by chriscook18** [comment]
At quick glance I can't see why the final print out number is so large at the end. My first thought is the 3 should be there but the 2767 is being added somewhere else - can't think where though.

Will look in more detail later

**Comment by abichown** [comment]
The problem was that there are 19 students, not 20. I have now corrected the program so it should be working.

**Comment by dougmet** [comment]
Yep, that's sorted it. This is what I now get:

```
1,14,2
2,30,3
3,37,2
4,5,1
5,24,1
6,9,3
7,6,1
8,27,1
9,21,1
10,4,1
11,58,3
12,47,2
13,22,1
14,57,1
15,51,2
16,52,1
17,34,1
18,15,2
19,44,2
Final energy: -90.593498
```

which looks pretty sensible

**Pull request merged**
